sonar.projectKey=tasklist-backend-fabre
sonar.projectName=Tasklist Backend Fabra
sonar.sources=src
sonar.exclusions=src/__tests__/**
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
